#DroneCI!!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: centos
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - /opt/maven/bin/mvn clean install
    - cd ..
    - docker build -t sampleimage .  
    - docker images
    #- docker image tag sampleimage:latest haripreethi.jfrog.io/default-docker-local/mydocker:latest
    - docker image tag sampleimage:latest hub.docker.com/repository/docker/haripreethisagar/new:latest
    - docker image push hub.docker.com/repository/docker/haripreethisagar/new:latest
    - docker login --username haripreethisagar --password Butki@123 https://hub.docker.com
    
#- name: publish  
  #image: hub.docker.com/repository/docker/haripreethisagar/new:latest
  #settings:
    #username:
      #from_secret: docker_username
    #password:
     # from_secret: docker_password
   # repo:  haripreethisagar/new
   # auto_tag: true
   # auto_tag_suffix: new-build
      
  






      
   
    
    
   
