#Droneci!!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
- name: build
  #pom-file: 'myapp/pom.xml'
  #goals: 'install'
  #options: /opt/maven
  commands:
     - cd myapp
     #- pwd
     #- mvn compile
     #- mvn package
    #- cd myapp
    #- mvn clean install
    #- pwd
    #- cd /
    #- pwd
    #- cat sample.txt
    - pwd
    - cd /
    - pwd
    - cd  /opt/maven
    - ls -ltr
    - maven compile 
    - maven package
    
    
   
