#DroneCI!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: centos
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - /opt/maven/bin/mvn clean install
    - cd ..
    - docker build -t sampleimage .  
    - docker images
    - docker image tag sampleimage:latest haripreethi.jfrog.io/default-docker-local/mydocker:latest
    - docker image push haripreethi.jfrog.io/default-docker-local/mydocker:latest
    - docker login --username preethi.sagar55@gmail.com --password Butki@123 https://haripreethi.jfrog.io/
    
#- name: publish  
  #image: sampleimage
  #settings:
   # username:
     # from_secret: jfrog_username
    #password:
     # from_secret: jfrog_password
   # repo: default-docker-local
    #auto_tag: true
    #auto_tag_suffix: drone-build
      
  






      
   
    
    
   
