#Droneci!!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
#- name: build
  #commands:
    #- cd myapp
    #- /opt/maven/bin/mvn clean install
  #  - whoami
  #  - pwd
    #- docker build -t myappdocker .
- name: artifactory
  image: athieriot/drone-artifactory 
  url: http://ec2-3-109-124-142.ap-south-1.compute.amazonaws.com:8082/
  username: admin
  password: password
  pom: pom.xml
  repo_key: sample
  files:
      - target/*.war
  force_upload: true
  #image: maven
  
  






      
   
    
    
   
