#Droneci!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    #- /opt/maven/bin/mvn compile
    #- /opt/maven/bin/mvn package
    - /opt/maven/bin/mvn clean install
    #- docker build --no-cache -t myappdocker .



      
   
    
    
   
