#Droneci!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
- name: build
  #pom-file: '/myapp/pom.xml'
  #goals: 'install'
  #options: /opt/maven
  commands:
     #- cd myapp
     #- pwd
     #- mvn compile
     #- mvn package
    #- cd myapp
    #- mvn clean install
    #- pwd
    #- cd /
    #- pwd
    #- cat sample.txt
    - cd myapp
    #- /opt/maven/bin/mvn compile
    #- /opt/maven/bin/mvn package
    - /opt/maven/bin/mvn clean install
    - pwd
    - ls -ltr
    #- cd target
    - cd ..
    - pwd
    - ls -ltr
    #- docker build --no-cache -t myappdocker .
- name: publish
  #image: ./*.war
  image: /home/haripreethi/.m2/repository/mydomain/myapp/0.1/myapp-0.1.war
  secrets: [ ARTIFACTORY_PASSWORD, ARTIFACTORY_USER, ARTIFACTORY_URL, REPOSITORY_KEY ]
  commands:
    # Download the JFrog CLI 
      - curl -fL https://getcli.jfrog.io | sh
      - ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
      - ./jfrog c show
   # Change the repository name in the configuration.yml to the the REPOSITORY_KEY.   
      #- sed -i 's,REPOSITORY_KEY,'"$REPOSITORY_KEY"',g' configuration.yml
      # Collect the environment variables with bce command
      #- ./jfrog rt bce myapp-0.1.war
      # Publish the build with bp command
      - ./jfrog rt bp myapp-0.1.war

  #settings:
    #username:
      #from_secret: jfrog_username
    #password:
      #from_secret: jfrog_password
    #repo: https://haripreethi.jfrog.io/ui/repos/tree/General/default-maven-local
      
   
    
    
   
