#DroneCI!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: ubuntu
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - /opt/maven/bin/mvn clean install
    #- docker build -t myappdocker .
    - docker build . --no-cache -t test:test
      
  






      
   
    
    
   
