#Droneci!!
kind: pipeline
type: ssh
name: default
server:
  host: 3.109.124.142
  user: ubuntu
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - /opt/maven/bin/mvn clean install
    - whoami
    - pwd
    #- docker build -t myappdocker .
- name: artifactory
  image: athieriot/drone-artifactory 
  url: http://ec2-3-109-124-142.ap-south-1.compute.amazonaws.com:8082/
  username: admin
  password: password
  pom: pom.xml
  repo_key: sample
  files:
      - target/*.war
  force_upload: true
  #secrets: [ ARTIFACTORY_PASSWORD, ARTIFACTORY_USER, ARTIFACTORY_URL, REPOSITORY_KEY ]
  #commands:
    # Download the JFrog CLI 
      #- curl -fL https://getcli.jfrog.io | sh
      #- ./jfrog config add --artifactory-url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD --interactive=false
      #- ./jfrog c show
      #- ./jfrog rt ping --url http://ec2-3-109-124-142.ap-south-1.compute.amazonaws.com:8082/
  
  






      
   
    
    
   
