#Droneci!!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
- name: build
  #pom-file: 'myapp/pom.xml'
  goals: 'install'
  options: /opt/maven
  commands:
     - cd myapp
     - mvn compile
     - mvn package
    #- cd myapp
    #- mvn clean install 
    
   
