#DroneCI!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: centos
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - mvn clean install
    - pwd
    - cd /home/centos/.m2/repository/mydomain/myapp/0.1
    - jar -xvf myapp-0.1.war
    #- curl -fL https://getcli.jfrog.io | sh
    #- chmod +x ./jfrog
    #- ./jfrog rt c --artifactory-url=https://haripreethi.jfrog.io/artifactory --user=preethi.sagar55@gmail.com --password=Butki@123
    #- apikey=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJQc285cDYwTE42QVRycFRlVmVrYlZMYjg1YTB3VUxabUFsZGxrUEpMUUZnIn0.eyJzdWIiOiJqZmZlQDAwMFwvdXNlcnNcL3ByZWV0aGkuc2FnYXI1NUBnbWFpbC5jb20iLCJzY3AiOiJhcHBsaWVkLXBlcm1pc3Npb25zXC9hZG1pbiBhcGk6KiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDAwIiwiaWF0IjoxNjMwMDU2ODcwLCJqdGkiOiI0MTE5MTM3Yi01OTRhLTQyZjQtOGRiNi0zM2FiMGE0MzY3ZGIifQ.aR5hDJcaS8hgk6-r0e4Ji04u7_GGa8aM2xLascOM11A_9iACHvYLp0v-GSAU7476jmyazgd8OynzlSmJxKIxqGBgT-Xwnfi1jXCqLqEMr2CWtVs6GiKJvfjJrURKSDnxf4OY0RY71qGloYrvN-WB-qDO92tv2TKBB0ZOXgocxQHNka3bfx1ipyK6DfgGrzfp_DL8508r3ZwFC7pTX8CBnXN1pVCW5lziKRhrUnf2txtCXENDYo6F7xap3XVk5MO7T7KRU2C5aJ2_mS8A-joEA_lYifx4nZa5VBxi9JEpcru6EqUZh-oX78qCylOyjjX0XEFxvQ3iQqQp2P6kRSj0Gg
    #- ./jfrog rt u --url=https://haripreethi.jfrog.io/artifactory --access-token=$apikey myapp/target/myapp-0.1.war maven/sample/myapp-0.1.war
    #- sudo docker build -t sampleimage .  
    #- sudo docker images
    #-  ./jfrog rt c --artifactory-url=https://haripreethi.jfrog.io/artifactory --access-token=$apikey sampledocker/sampleimage
    #- docker login -u haripreethisagar -p Butki@123 https://hub.docker.com/     cat ~/my_password.txt | docker login --username foo --password-stdin
    #- pwd
    #- docker login --username haripreethisagar --password $password
    #- docker tag sampleimage:latest haripreethi.jfrog.io/sampledocker:latest
    #- docker push haripreethi.jfrog.io/sampledocker:latest
    
    
    
   
    
   
    

      
  






      
   
    
    
   
