#DroneCI!
kind: pipeline
type: ssh
name: default
server:
  host: 13.126.193.83
  user: centos
  password:
    from_secret: ssh_password
steps:
- name: build
  commands:
    - cd myapp
    - /opt/maven/bin/mvn clean install
    - cd ..
    #- docker build -t myappdocker .
    - sudo docker build -t sampleimage . 
      
  






      
   
    
    
   
